export const SPOT_TYPES = [
  { id: 'Stairset', name: 'Stairset' },
  { id: 'Gap', name: 'Gap' },
  { id: 'Handrail', name: 'Handrail' },
  { id: 'Manual Pad', name: 'Manual Pad' },
  { id: 'Bank', name: 'Bank' },
  { id: 'Quarterpipe', name: 'Quarterpipe' },
  { id: 'Halfpipe', name: 'Halfpipe' },
  { id: 'Bowl', name: 'Bowl' },
  { id: 'Flatbar', name: 'Flatbar' },
  { id: 'Hubba', name: 'Hubba' },
  { id: 'Mini Ramp', name: 'Mini Ramp' },
  { id: 'Hill Bomb', name: 'Hill Bomb' },
  { id: 'Curb', name: 'Curb' },
  { id: 'Ledge', name: 'Ledge' },
  { id: 'Grind', name: 'Grind' },
  { id: 'Park', name: 'Park' },
  { id: 'DIY', name: 'DIY' },
  { id: 'Other', name: 'Other' },
];